const {chromium,expect}=require('@playwright/test');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch();const p=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];p.on('pageerror',e=>errors.push(e.message));let creates=0,uploads=[];const required=['loan_application','identity_income','bank_statement','credit_bureau','business_registration','financial_statement','gst_return','debt_schedule','projected_cashflow'];
 await p.route('**/api/v1/applications',async route=>{if(route.request().method()!=='POST')return route.continue();creates++;const body=route.request().postDataJSON();assert.equal(body.product,'term_loan');return route.fulfill({json:{id:'intake-ui-test',required_documents:required,status:'draft',...body}})});
 await p.route('**/api/v1/applications/intake-ui-test/documents',async route=>{uploads.push(route.request().postDataBuffer().toString());return route.fulfill({json:{id:'document-'+uploads.length,status:'uploaded'}})});
 await p.route('**/api/v1/applications/intake-ui-test',route=>route.fulfill({status:404,json:{detail:'UI test complete; no customer record was persisted.'}}));
 async function start(){await p.goto('http://localhost:3000/loan-origination');await p.getByRole('button',{name:'New application',exact:true}).click();await p.getByRole('textbox',{name:'Borrower name',exact:true}).fill('UI Test Borrower');await p.getByRole('button',{name:'Facility',exact:true}).click();await expect(p.getByRole('listbox',{name:'Facility'})).toBeVisible();assert.equal(await p.locator('select:visible').count(),0);await p.getByRole('option',{name:'Business term loan',exact:true}).click();await p.getByRole('spinbutton',{name:'Requested amount (INR)',exact:true}).fill('200000');await p.getByRole('textbox',{name:'Business sector',exact:true}).fill('Salaried');await p.getByRole('button',{name:'Continue to required documents'}).click();await expect(p.getByRole('heading',{name:'Do you have these documents ready?'})).toBeVisible();}
 await start();await p.getByRole('button',{name:'No, not yet'}).click();await expect(p.getByRole('alertdialog')).toContainText('Draft');assert.equal(creates,0);await p.getByRole('button',{name:'Save as draft',exact:true}).click();await expect(p).toHaveURL(/intake-ui-test\/documents/);assert.equal(creates,1);
 await start();await p.getByRole('button',{name:'Yes, upload documents'}).click();await expect(p.getByText('Document 1 of 9',{exact:true})).toBeVisible();for(let i=0;i<required.length;i++){await p.locator('input[type=file]').setInputFiles({name:'evidence-'+i+'.csv',mimeType:'text/csv',buffer:Buffer.from('date,amount\n2026-01-01,100')});await p.getByRole('button',{name:'Upload and continue',exact:true}).click();if(i<required.length-1)await expect(p.getByText('Document '+(i+2)+' of 9',{exact:true})).toBeVisible();}await expect(p.getByRole('heading',{name:'Required documents uploaded',exact:true})).toBeVisible();assert.equal(creates,2);assert.equal(uploads.length,9);required.forEach((key,i)=>assert.ok(uploads[i].includes(key)));await p.screenshot({path:'../artifacts/intake-complete.png'});
 await p.getByRole('button',{name:'Close',exact:true}).click();await p.getByRole('button',{name:'New application',exact:true}).click();await p.getByRole('button',{name:'Facility',exact:true}).click();await p.screenshot({path:'../artifacts/inline-select-desktop.png'});await p.setViewportSize({width:390,height:844});await p.screenshot({path:'../artifacts/inline-select-mobile.png'});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: themed inline options; no-documents draft confirmation; all nine sequential uploads; product-specific checklist; desktop/mobile captures. API writes mocked.');})().catch(e=>{console.error(e);process.exit(1)});
