'use client';
import {useState,useRef} from 'react';
import {CheckCircle2,FileText,Upload} from 'lucide-react';
import InlineSelect from './inline-select';
import {api,Data,label} from './api';
export default function ApplicationIntake({products,documents,done,cancel}:{products:Data[],documents:Data[],done:(id:string)=>void,cancel:()=>void}){
 const [product,setProduct]=useState(products[0]?.key||'');const [values,setValues]=useState<Data>({});const [stage,setStage]=useState('details');const [caseId,setCaseId]=useState('');const [required,setRequired]=useState<string[]>([]);const [index,setIndex]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [file,setFile]=useState<File|null>(null);const [received,setReceived]=useState<string[]>([]);const createKey=useRef(crypto.randomUUID());const uploadKey=useRef(crypto.randomUUID());
 const current=products.find(p=>p.key===product);const checklist=caseId?required:current?.documents||[];const doc=(key:string)=>documents.find(d=>d.key===key)||{label:label(key),purpose:'Required supporting evidence for this facility.'};
 async function create(){if(caseId)return caseId;const c=await api('/applications',{...values,product,tenure:Number(values.tenure)},undefined,createKey.current);setCaseId(c.id);setRequired(c.required_documents||checklist);return c.id}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="document-intake">{error&&<div role="alert" className="alert warning">{error}</div>}
 {stage==='details'?<form onSubmit={e=>{e.preventDefault();setValues(Object.fromEntries(new FormData(e.currentTarget)));setStage('readiness')}}><p>Step 1 · Borrower and facility details</p><div className="form-grid"><label className="span-two">Borrower name<input name="borrower" required minLength={2} defaultValue={values.borrower} placeholder="Registered business name"/></label><label>Borrower segment<InlineSelect name="business_segment" aria-label="Borrower segment" defaultValue={values.business_segment||'msme'}><option value="msme">MSME</option><option value="enterprise">Enterprise</option></InlineSelect></label><label>Facility<InlineSelect aria-label="Facility" value={product} onChange={e=>setProduct(e.target.value)}>{products.map(p=><option key={p.key} value={p.key}>{p.name}</option>)}</InlineSelect></label><label>Requested amount (INR)<input name="amount" type="number" required min="1" defaultValue={values.amount||''}/></label><label>Tenure (months)<input name="tenure" type="number" required min={current?.min_tenure||1} max={current?.max_tenure||600} defaultValue={values.tenure||12}/></label><label>Business sector<input name="sector" defaultValue={values.sector||''} required/></label><label>Branch<InlineSelect name="branch" aria-label="Branch" defaultValue={values.branch||'Mumbai'}>{['Mumbai','Pune','Ahmedabad','Bengaluru'].map(b=><option key={b}>{b}</option>)}</InlineSelect></label></div><div className="modal-footer"><button type="button" className="btn" onClick={cancel}>Cancel</button><button className="btn primary" disabled={!product}>Continue to required documents</button></div></form>:<>
 <p>Step 2 · Required documents for {current?.name}</p><div className="checklist">{checklist.map((key:string)=><div key={key}>{received.includes(key)?<CheckCircle2 size={17}/>:<FileText size={17}/>}<span>{doc(key).label}</span></div>)}</div>
 {stage==='readiness'&&<><h2>Do you have these documents ready?</h2><p>Check the list above before starting the upload.</p><div className="choice-actions"><button className="btn primary" disabled={busy} onClick={()=>run(async()=>{await create();setStage(checklist.length?'upload':'complete')})}>Yes, upload documents</button><button className="btn" disabled={busy} onClick={()=>setStage('draft')}>No, not yet</button><button className="text-link" onClick={()=>setStage('details')}>Back to application details</button></div></>}
 {stage==='draft'&&<div role="alertdialog" aria-label="Save application as draft" className="draft-notice"><h2>We’ll keep this application in Draft</h2><p>It will remain in Draft until documents are uploaded. You can return to the application’s Documents tab whenever they are ready.</p><div className="choice-actions"><button className="btn primary" disabled={busy} onClick={()=>run(async()=>done(await create()))}>{busy?'Saving…':'Save as draft'}</button><button className="btn" disabled={busy} onClick={()=>setStage('readiness')}>Go back</button></div></div>}
 {stage==='upload'&&<><p>Document {index+1} of {checklist.length}</p><h2>{doc(checklist[index]).label}</h2><p>{doc(checklist[index]).purpose}</p><p>PDF, PNG, JPEG or CSV · Maximum 25 MB · PDFs up to 100 pages.</p><input key={index} aria-label={'Upload '+doc(checklist[index]).label} type="file" accept=".pdf,.png,.jpg,.jpeg,.csv" disabled={busy} onChange={e=>{setError('');uploadKey.current=crypto.randomUUID();const f=e.target.files?.[0]||null;if(f&&f.size>25*1024*1024){setError('This file is larger than 25 MB. Choose a smaller file.');setFile(null)}else setFile(f)}}/><div className="choice-actions"><button className="btn primary" disabled={busy||!file} onClick={()=>run(async()=>{const form=new FormData();form.append('file',file!);form.append('document_type',checklist[index]);const uploaded=await api('/applications/'+caseId+'/documents',form,undefined,uploadKey.current);if(uploaded.status==='locked'){setError('This PDF is locked. It was saved for review; upload an unlocked replacement in the Documents tab.');return}setReceived(v=>[...v,checklist[index]]);setFile(null);if(index+1===checklist.length)setStage('complete');else setIndex(index+1)})}><Upload size={16}/>{busy?'Uploading…':'Upload and continue'}</button><button className="btn" disabled={busy} onClick={()=>done(caseId)}>Save progress & finish later</button></div><p>Uploaded files are saved immediately. They still require extraction and verification.</p></>}
 {stage==='complete'&&<><h2>Required documents uploaded</h2><p>The application is ready for document review. Uploading evidence does not approve the loan.</p><button className="btn primary" onClick={()=>done(caseId)}>Open document review</button></>}
 </>}
 </div>
}
