'use client';
import InlineSelect from './inline-select';
import {useState} from 'react';
import {api,Data,money,day} from './api';
export default function CustomerCredit({detail,refresh,report,review,canReview}:{detail:Data,refresh:()=>Promise<void>,report:(s:string)=>void,review:(key:string)=>void,canReview:boolean}){
 const latest=detail.debt_schedule?.[0];const [edit,setEdit]=useState(false),[busy,setBusy]=useState(false),[loans,setLoans]=useState<Data[]>([]);
 const blank=()=>({lender:'',loan_type:'',monthly_emi:'',outstanding:'',dpd:'',status:'active',repayment_history:''});
 return <section className="panel" style={{marginBottom:22}}><div className="panel-heading"><div><h2>Customer obligations & repayment history</h2><p>Assigned employee: <strong>{detail.application.owner||'Unassigned'}</strong> · {detail.application.reference}</p></div>{canReview&&<button className="btn" onClick={()=>{setLoans(latest?.loans?.map((l:Data)=>({...l}))||[blank()]);setEdit(!edit)}}>{edit?'Cancel':'Review previous loans'}</button>}</div><div className="bureau-metrics" style={{padding:22}}>{[['existing_emi','Existing monthly EMI'],['proposed_emi','Proposed monthly EMI'],['monthly_income','Net monthly income']].map(([k,n])=><div key={k}><span>{n}</span><strong>{detail.facts[k]==null?'Not recorded':money(detail.facts[k])}</strong><p>{k==='proposed_emi'?'From the application repayment quote':k==='existing_emi'?'Total active monthly loan obligations':'Use verified take-home income'}</p>{canReview&&k==='monthly_income'&&<button className="text-link" onClick={()=>review(k)}>Enter / correct income</button>}</div>)}</div>{!latest&&!edit&&<p className="metric-definition">No reviewed previous-loan schedule is recorded. A missing EMI is unknown, not zero. Add the schedule or explicitly confirm that the customer has no existing loans.</p>}
 {edit&&<form style={{padding:22}} onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);try{await api(`/applications/${detail.application.id}/debt-schedule`,{loans,complete:fd.get('complete')==='on',no_existing_loans:loans.length===0&&fd.get('no_loans')==='on',report_date:fd.get('report_date'),source_text:fd.get('source_text'),document_id:fd.get('document_id'),expected_version:detail.application.version});setEdit(false);await refresh()}catch(e){report((e as Error).message)}finally{setBusy(false)}}}>{loans.map((l,i)=><fieldset key={i} style={{padding:16,marginBottom:16}}><legend>Previous loan {i+1}</legend><div className="form-grid">{[['lender','Lender'],['loan_type','Loan type'],['monthly_emi','Monthly EMI (INR)'],['outstanding','Outstanding balance (INR)'],['dpd','Reported days past due']].map(([k,n])=><label key={k}>{n}<input required={k!=='loan_type'&&k!=='dpd'} type={['monthly_emi','outstanding','dpd'].includes(k)?'number':'text'} min="0" step={k==='dpd'?'1':'any'} value={l[k]??''} onChange={e=>setLoans(loans.map((x,j)=>j===i?{...x,[k]:e.target.value}:x))}/></label>)}<label>Status<InlineSelect value={l.status} onChange={e=>setLoans(loans.map((x,j)=>j===i?{...x,status:e.target.value}:x))}><option value="active">Active</option><option value="closed">Closed</option></InlineSelect></label><label className="span-two">Reported repayment history<textarea placeholder="Record source-supported payment dates, missed instalments or settlement details. Leave blank if unknown." value={l.repayment_history} onChange={e=>setLoans(loans.map((x,j)=>j===i?{...x,repayment_history:e.target.value}:x))}/></label></div><button className="text-link" type="button" onClick={()=>setLoans(loans.filter((_,j)=>j!==i))}>Remove loan</button></fieldset>)}<button type="button" className="btn" onClick={()=>setLoans([...loans,blank()])}>Add previous loan</button><div className="form-grid" style={{marginTop:18}}><label>Report date<input type="date" name="report_date" required max={new Date().toISOString().slice(0,10)}/></label><label>Source document<InlineSelect name="document_id"><option value="">Other reviewed source — explain below</option>{detail.document.map((d:Data)=><option key={d.id} value={d.id}>{d.filename}</option>)}</InlineSelect></label><label className="span-two">Source reference and review explanation<textarea name="source_text" required minLength={10}/></label><label className="span-two"><input type="checkbox" name="complete" required/> I verified the complete existing-loan schedule.</label>{!loans.length&&<label className="span-two"><input type="checkbox" name="no_loans" required/> I verified that the customer has no existing loans.</label>}</div><button className="btn primary" disabled={busy}>Save reviewed debt schedule</button></form>}
 {latest&&<><div className="table-scroll"><table><thead><tr><th>Lender / facility</th><th>Monthly EMI</th><th>Outstanding</th><th>Days past due</th><th>Status</th><th>Repayment history</th></tr></thead><tbody>{latest.loans.map((l:Data,i:number)=><tr key={i}><td>{l.lender}<small>{l.loan_type}</small></td><td>{money(l.monthly_emi)}</td><td>{money(l.outstanding)}</td><td>{l.dpd??'Not reported'}</td><td>{l.status}</td><td>{l.repayment_history||'Not reported'}</td></tr>)}</tbody></table></div><p className="metric-definition">{latest.loans.length?'':'No existing loans confirmed. '}As of {latest.report_date} · Reviewed by {latest.reviewer} · {latest.source_text}</p><details style={{padding:22}}><summary>Earlier debt-schedule reviews ({Math.max(0,detail.debt_schedule.length-1)})</summary>{detail.debt_schedule.slice(1).map((s:Data)=><p key={s.id}>{s.report_date} · Existing EMI {money(s.total_monthly_emi)} · {s.reviewer} · {s.source_text}</p>)}</details></>}
 </section>
}
