'use client';
import {useState} from 'react';
import {Data,money} from './api';
import {fieldLabel} from './financial-expression';
export default function EvidenceReview({detail,review,showSource,canReview}:{detail:Data;review:(key:string)=>void;showSource:(id:string)=>Promise<void>;canReview:boolean}){
 const [filter,setFilter]=useState('all'),[query,setQuery]=useState('');
 const definitions=detail.assessment?.[0]?.snapshot?.policy?.fields||[];
 const entries=Object.entries(detail.sources||{}) as [string,Data][];
 const pending=entries.filter(([,v])=>!v.verified).length;
 const name=(key:string)=>definitions.find((f:Data)=>f.key===key)?.label||fieldLabel(key);
 function value(key:string,v:Data){if(v.value==null||v.value==='')return 'Not recorded';const def=definitions.find((f:Data)=>f.key===key);const unit=v.unit||def?.unit;const number=Number(v.value);if(!Number.isFinite(number)||def?.type==='date')return String(v.value);if(unit==='INR')return money(v.value);return number.toLocaleString('en-IN')+(unit==='percent'?'%':unit&&unit!=='number'?' '+unit:'');}
 const visible=entries.filter(([key,v])=>(filter==='all'||(filter==='pending'?!v.verified:v.verified))&&name(key).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(!!a[1].verified)-Number(!!b[1].verified)||name(a[0]).localeCompare(name(b[0])));
 return <section className="panel full-span evidence-review"><div className="panel-heading"><div><h2>Financial information to verify</h2><p>Compare each value with its source, then confirm or correct it. Extracted values are not automatically verified.</p></div></div><div className="evidence-toolbar"><div className="evidence-filters" aria-label="Filter financial information">{[['all',`All values (${entries.length})`],['pending',`Needs review (${pending})`],['verified',`Verified (${entries.length-pending})`]].map(([key,title])=><button key={key} className={'btn small-btn '+(filter===key?'primary':'')} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{title}</button>)}</div><input aria-label="Search financial information" placeholder="Search a financial item…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="table-scroll"><table><thead><tr><th>Financial item</th><th className="num">Recorded value</th><th>Reporting period</th><th>Source evidence</th><th>Review status</th><th>Action</th></tr></thead><tbody>{visible.map(([key,v])=>{const doc=detail.document.find((d:Data)=>d.id===v.document_id);return <tr key={key}><td><strong>{name(key)}</strong></td><td className="num">{value(key,v)}</td><td>{v.period||'Not specified'}</td><td>{v.document_id?<button className="text-link" onClick={()=>showSource(v.document_id)}>{doc?.filename||'Open source document'}<small>Page {v.page||1}</small></button>:<span>{v.source_text||'No source reference recorded'}</span>}</td><td><span className={'badge '+(v.verified?'verified':'warning')}>{v.verified?'Verified':'Needs review'}</span>{v.reviewer&&<small>{v.reviewer}</small>}</td><td>{canReview?<button className="btn small-btn" onClick={()=>review(key)}>{v.verified?'View / correct':'Review value'}</button>:<span className="muted">Reviewer access required</span>}</td></tr>})}</tbody></table></div>{!visible.length&&<p className="evidence-empty">{entries.length?'No values match this filter.':'Upload and extract a document to see its financial information here.'}</p>}</section>
}
