'use client';
import {Children,isValidElement,useId,useRef,useState,SelectHTMLAttributes} from 'react';
import {ChevronDown,Check} from 'lucide-react';
// The options participate in layout: no browser popup, portal or floating menu.
export default function InlineSelect(props:SelectHTMLAttributes<HTMLSelectElement>){
 const {children,value,defaultValue,onChange,className,...rest}=props;const id=useId();const ref=useRef<HTMLButtonElement>(null);const [open,setOpen]=useState(false);const [local,setLocal]=useState(defaultValue);
 const options:any[]=[];function collect(nodes:any){Children.forEach(nodes,n=>{if(isValidElement<any>(n)){if(n.type==='option')options.push({value:String(n.props.value??n.props.children),label:n.props.children,disabled:n.props.disabled});else if(n.props.children)collect(n.props.children)}})}collect(children);
 const selected=String(value??local??options[0]?.value??'');
 function choose(v:string){setLocal(v);setOpen(false);onChange?.({target:{value:v},currentTarget:{value:v}} as any);ref.current?.focus()}
 return <span className={'inline-select '+(className||'')}><select {...rest} value={selected} onChange={onChange} hidden tabIndex={-1} aria-hidden="true">{children}</select><button ref={ref} id={props.id?props.id+'-control':undefined} type="button" className="select-trigger" disabled={props.disabled} aria-label={props['aria-label']||props.name} aria-expanded={open} aria-controls={id} onClick={()=>setOpen(!open)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);requestAnimationFrame(()=>document.getElementById(id)?.querySelector<HTMLElement>('[aria-selected="true"]')?.focus())}if(e.key==='Escape'&&open){e.preventDefault();e.stopPropagation();setOpen(false)}}}><span>{options.find(o=>o.value===selected)?.label||'Select an option'}</span><ChevronDown size={16}/></button>{open&&<span id={id} role="listbox" aria-label={props['aria-label']||props.name||'Options'} className="inline-options" onKeyDown={e=>{const items=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)'));const i=items.indexOf(document.activeElement as HTMLButtonElement);if(e.key==='Escape'){e.preventDefault();e.stopPropagation();setOpen(false);ref.current?.focus()}if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();items[e.key==='Home'?0:e.key==='End'?items.length-1:(i+(e.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus()}}}>{options.map((o,i)=><button type="button" role="option" key={o.value+'-'+i} disabled={o.disabled} aria-selected={selected===o.value} onClick={()=>choose(o.value)}>{o.label}{selected===o.value&&<Check size={15}/>}</button>)}</span>}</span>
}
