'use client';
import {useEffect,useState} from 'react';
import {BriefcaseBusiness,CheckCircle2,Percent,ShieldAlert,Users,Wallet,LayoutDashboard,UserRound,GitBranch,ShieldCheck,Trophy} from 'lucide-react';
import {Data,money,label} from './api';

// Categorical order validated for the white chart surface (dataviz validator, adjacent pairs). Never cycled: extra slices fold into "Other".
const SERIES=['#2a78d6','#eb6834','#1baf7a','#eda100','#e87ba4','#4a3aa7'];
const OTHER='#9aa5b1';
const STATUS_COLORS:Record<string,string>={approved:'#177760',declined:'#b44545',rejected:'#b44545',draft:'#8594aa',evidence_pending:'#966321',in_review:'#2a78d6',pending_approval:'#7254a3',returned:'#bb751d',withdrawn:'#596a7e',active:'#2a78d6'};
const STAGES=['draft','evidence_pending','in_review','pending_approval','approved','declined','withdrawn'];
const VIEWS=[{id:'portfolio',name:'Portfolio summary',icon:LayoutDashboard,help:'Total business, loan mix and outcomes'},{id:'team',name:'Team performance',icon:UserRound,help:'Customers and credit handled by each employee'},{id:'pipeline',name:'Pipeline & ageing',icon:GitBranch,help:'Where applications sit and how long they have waited'},{id:'risk',name:'Risk & compliance',icon:ShieldCheck,help:'Exceptions, bureau scores and document gaps'}];
type Slice={key:string,name:string,value:number,display?:string,color?:string};
// Severity is a state, so it wears the reserved status colours (always shown with a text label).
const SEVERITY:Record<string,string>={blocking:'#b44545',critical:'#b44545',high:'#b44545',warning:'#966321',medium:'#966321',low:'#596a7e',info:'#596a7e'};
const pct=(n:number,d:number)=>d?Math.round(n/d*100):0;
const sum=(xs:Data[],f:(c:Data)=>number)=>xs.reduce((s,c)=>s+f(c),0);

function fold(slices:Slice[],limit=SERIES.length-1):Slice[]{const sorted=[...slices].filter(s=>s.value>0).sort((a,b)=>b.value-a.value);if(sorted.length<=limit+1)return sorted;const rest=sorted.slice(limit);return [...sorted.slice(0,limit),{key:'__other',name:`Other (${rest.length})`,value:rest.reduce((s,x)=>s+x.value,0)}]}

function Donut({title,caption,slices,total,totalLabel,format=(n:number)=>String(n),onSelect,statusColors=false}:{title:string,caption:string,slices:Slice[],total:string,totalLabel:string,format?:(n:number)=>string,onSelect?:(key:string)=>void,statusColors?:boolean}){
 const [hover,setHover]=useState<string|null>(null);const all=slices.reduce((s,x)=>s+x.value,0);const R=70,r=46,C=90;let angle=-Math.PI/2;
 const arcs=slices.map((s,i)=>{const sweep=all?s.value/all*Math.PI*2:0;const a0=angle,a1=angle+sweep;angle=a1;const large=sweep>Math.PI?1:0;const p=(rad:number,a:number)=>`${C+rad*Math.cos(a)} ${C+rad*Math.sin(a)}`;const full=sweep>=Math.PI*2-1e-6;const d=full?`M ${p(R,a0)} A ${R} ${R} 0 1 1 ${p(R,a0+Math.PI)} A ${R} ${R} 0 1 1 ${p(R,a0)} M ${p(r,a0)} A ${r} ${r} 0 1 0 ${p(r,a0+Math.PI)} A ${r} ${r} 0 1 0 ${p(r,a0)} Z`:`M ${p(R,a0)} A ${R} ${R} 0 ${large} 1 ${p(R,a1)} L ${p(r,a1)} A ${r} ${r} 0 ${large} 0 ${p(r,a0)} Z`;return {...s,d,color:s.color||(statusColors?(STATUS_COLORS[s.key]||OTHER):(s.key==='__other'?OTHER:SERIES[i]))}});
 const active=arcs.find(a=>a.key===hover);
 return <section className="panel chart-panel"><div className="panel-heading"><div><h2>{title}</h2><p>{caption}</p></div></div>{!all?<p className="chart-empty">No data for the current filters.</p>:<div className="donut-body"><div className="donut-wrap"><svg viewBox="0 0 180 180" role="img" aria-label={`${title}: ${arcs.map(a=>`${a.name} ${a.display||format(a.value)}`).join(', ')}`}>{arcs.map(a=><path key={a.key} d={a.d} fill={a.color} stroke="#fff" strokeWidth={2} fillRule="evenodd" opacity={hover&&hover!==a.key?.45:1} onMouseEnter={()=>setHover(a.key)} onMouseLeave={()=>setHover(null)} onClick={()=>onSelect&&a.key!=='__other'&&onSelect(a.key)} style={{cursor:onSelect&&a.key!=='__other'?'pointer':'default'}}/>)}</svg><div className="donut-center">{active?<><strong>{pct(active.value,all)}%</strong><small>{active.name}</small></>:<><strong>{total}</strong><small>{totalLabel}</small></>}</div></div><ul className="chart-legend">{arcs.map(a=><li key={a.key}><button type="button" disabled={!onSelect||a.key==='__other'} onMouseEnter={()=>setHover(a.key)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(a.key)} onBlur={()=>setHover(null)} onClick={()=>onSelect&&onSelect(a.key)}><i style={{background:a.color}}/><span>{a.name}</span><b>{a.display||format(a.value)}</b><small>{pct(a.value,all)}%</small></button></li>)}</ul></div>}</section>
}

function Bars({title,caption,rows,format=(n:number)=>String(n),highlight,note}:{title:string,caption:string,rows:{key:string,name:string,value:number,sub?:string}[],format?:(n:number)=>string,highlight?:string,note?:React.ReactNode}){
 const max=Math.max(...rows.map(r=>r.value),1);
 return <section className="panel chart-panel"><div className="panel-heading"><div><h2>{title}</h2><p>{caption}</p></div></div>{!rows.length?<p className="chart-empty">No data for the current filters.</p>:<><div className="hbar-list">{rows.map(r=><div className={'hbar-row'+(r.key===highlight?' top':'')} key={r.key} title={`${r.name}: ${format(r.value)}${r.sub?' · '+r.sub:''}`}><span className="hbar-name">{r.name}{r.key===highlight&&<Trophy size={13} aria-label="Highest"/>}</span><span className="hbar-track"><em style={{width:`${Math.max(2,r.value/max*100)}%`}}/></span><b>{format(r.value)}</b>{r.sub&&<small>{r.sub}</small>}</div>)}</div>{note&&<p className="chart-note">{note}</p>}</>}</section>
}

export default function OverviewDashboards({cases,exceptions,pipeline,insights,attention,onStage,onProduct,onExceptions}:{cases:Data[],exceptions:Data[],pipeline:React.ReactNode,insights:React.ReactNode,attention:React.ReactNode,onStage:(s:string)=>void,onProduct:(p:string)=>void,onExceptions:()=>void}){
 const [view,setView]=useState('portfolio');
 useEffect(()=>{try{const v=localStorage.getItem('ledger.overview.view');if(v&&VIEWS.some(x=>x.id===v))setView(v)}catch{}},[]);
 function choose(v:string){setView(v);try{localStorage.setItem('ledger.overview.view',v)}catch{}}
 const requested=sum(cases,c=>Number(c.amount)||0),sanctioned=sum(cases,c=>Number(c.sanctioned_amount)||0);
 const approved=cases.filter(c=>c.status==='approved'),decided=cases.filter(c=>['approved','declined'].includes(c.status));
 const active=cases.filter(c=>!['approved','declined','withdrawn'].includes(c.status));
 const customers=new Set(cases.map(c=>String(c.borrower||c.id).trim().toLowerCase())).size;
 const employees=Array.from(new Set(cases.map(c=>c.owner_id||'unassigned'))).map(id=>{const own=cases.filter(c=>(c.owner_id||'unassigned')===id);return {id:String(id),name:own[0]?.owner||'Unassigned',cases:own,customers:new Set(own.map(c=>String(c.borrower||c.id).trim().toLowerCase())).size,requested:sum(own,c=>Number(c.amount)||0),sanctioned:sum(own,c=>Number(c.sanctioned_amount)||0),approved:own.filter(c=>c.status==='approved').length,pending:own.filter(c=>c.status==='pending_approval').length,review:own.filter(c=>c.status==='in_review').length}}).sort((a,b)=>b.customers-a.customers||b.requested-a.requested);
 const top=employees.find(e=>e.id!=='unassigned')||employees[0];
 const totals=[
  {name:'Total applications',value:String(cases.length),sub:`${active.length} active in the pipeline`,icon:BriefcaseBusiness,go:()=>onStage('all')},
  {name:'Total customers',value:String(customers),sub:`Handled by ${employees.filter(e=>e.id!=='unassigned').length} employees`,icon:Users,go:()=>choose('team')},
  {name:'Total credit requested',value:money(requested,true),sub:money(requested),icon:Wallet,go:()=>onStage('all')},
  {name:'Total credit sanctioned',value:money(sanctioned,true),sub:`${approved.length} approved applications`,icon:CheckCircle2,go:()=>onStage('approved')},
  {name:'Approval rate',value:decided.length?pct(approved.length,decided.length)+'%':'—',sub:decided.length?`${approved.length} of ${decided.length} decided cases`:'No decisions recorded yet',icon:Percent,go:()=>onStage('approved')},
  {name:'Open exceptions',value:String(exceptions.length),sub:'Evidence and policy referrals',icon:ShieldAlert,go:onExceptions,warn:exceptions.length>0},
 ];
 const statusSlices=Array.from(new Set([...STAGES,...cases.map(c=>c.status)])).map(s=>({key:s,name:label(s),value:cases.filter(c=>c.status===s).length})).filter(s=>s.value>0);
 const productSlices=fold(Array.from(new Set(cases.map(c=>String(c.product)))).map(p=>({key:p,name:label(p),value:sum(cases.filter(c=>c.product===p),c=>Number(c.amount)||0)})));
 const teamSlices=fold(employees.map(e=>({key:e.id,name:e.name,value:e.customers})));
 const now=Date.now();const ageBands=[{key:'0-7',name:'0–7 days',min:0,max:7},{key:'8-15',name:'8–15 days',min:8,max:15},{key:'16-30',name:'16–30 days',min:16,max:30},{key:'30+',name:'Over 30 days',min:31,max:Infinity}];
 const ages=active.map(c=>c.created_at?Math.floor((now-new Date(c.created_at).getTime())/864e5):null).filter((d):d is number=>d!=null&&d>=0);
 const scoreBands=[{key:'lt650',name:'Below 650',test:(s:number)=>s<650},{key:'650',name:'650–699',test:(s:number)=>s>=650&&s<700},{key:'700',name:'700–749',test:(s:number)=>s>=700&&s<750},{key:'750',name:'750 and above',test:(s:number)=>s>=750}];
 const scores=cases.map(c=>c.bureau?.promoter_cibil_score).filter(v=>v!=null&&Number(v)>=300&&Number(v)<=900).map(Number);
 const severities=Array.from(new Set(exceptions.map(e=>String(e.severity||'unspecified'))));
 const docsComplete=cases.filter(c=>Number(c.documents_received)>=Number(c.documents_required)).length;
 return <>
  <div className="totals-strip" aria-label="Portfolio totals">{totals.map(t=><button type="button" key={t.name} onClick={t.go}><span>{t.name}<t.icon size={16}/></span><strong className={t.warn?'amber-text':''}>{t.value}</strong><small>{t.sub}</small></button>)}</div>
  <div className="dashboard-tabs" role="tablist" aria-label="Dashboard type">{VIEWS.map(v=><button type="button" role="tab" key={v.id} aria-selected={view===v.id} className={view===v.id?'active':''} onClick={()=>choose(v.id)}><v.icon size={16}/><span><strong>{v.name}</strong><small>{v.help}</small></span></button>)}</div>
  <div role="tabpanel" aria-label={VIEWS.find(v=>v.id===view)?.name}>
  {view==='portfolio'&&<><div className="chart-grid"><Donut statusColors title="Applications by status" caption="Share of all applications at each stage · click a slice to open the list" slices={statusSlices} total={String(cases.length)} totalLabel="Total applications" onSelect={onStage}/><Donut title="Credit requested by loan type" caption="Share of total requested credit (INR) · click a slice to filter" slices={productSlices} total={money(requested,true)} totalLabel="Total requested" format={n=>money(n,true)} onSelect={onProduct}/></div>{insights}</>}
  {view==='team'&&<><div className="chart-grid"><Bars title="Customers handled by each employee" caption="Unique customers across current applications · highest first" rows={employees.map(e=>({key:e.id,name:e.name,value:e.customers,sub:`${e.cases.length} applications`}))} highlight={top?.id} note={top&&top.customers>0?<><strong>{top.name}</strong> is handling the most customers: {top.customers} of {customers} ({pct(top.customers,customers)}% of the total).</>:null}/><Donut title="Share of customers by employee" caption="Each employee's part of the total customer base" slices={teamSlices} total={String(customers)} totalLabel="Total customers"/></div>
   <section className="panel"><div className="panel-heading"><div><h2>Employee performance table</h2><p>Totals per employee for the current filters</p></div></div><div className="table-scroll"><table><thead><tr><th>Employee</th><th>Customers</th><th>Applications</th><th>In review</th><th>Pending approval</th><th>Approved</th><th>Credit requested</th><th>Credit sanctioned</th></tr></thead><tbody>{employees.map(e=><tr key={e.id}><td>{e.name}</td><td>{e.customers}</td><td>{e.cases.length}</td><td>{e.review}</td><td>{e.pending}</td><td>{e.approved}</td><td>{money(e.requested)}</td><td>{money(e.sanctioned)}</td></tr>)}<tr className="total-row"><td>Total</td><td>{customers}</td><td>{cases.length}</td><td>{employees.reduce((n,e)=>n+e.review,0)}</td><td>{employees.reduce((n,e)=>n+e.pending,0)}</td><td>{approved.length}</td><td>{money(requested)}</td><td>{money(sanctioned)}</td></tr></tbody></table></div></section></>}
  {view==='pipeline'&&<><section className="panel pipeline-panel"><div className="panel-heading"><div><h2>Credit pipeline</h2><p>Requested credit (INR) by application stage · click a bar to open the list</p></div><span className="subtle-label">Total {money(requested,true)}</span></div>{pipeline}</section><div className="chart-grid"><Bars title="Active applications by age" caption="Days since the application was created · active cases only" rows={ageBands.map(b=>({key:b.key,name:b.name,value:ages.filter(d=>d>=b.min&&d<=b.max).length}))} format={n=>n+' cases'} note={<>Total active: <strong>{active.length}</strong> applications{ages.length?<> · average age <strong>{Math.round(ages.reduce((s,d)=>s+d,0)/ages.length)} days</strong></>:null}.</>}/><Donut statusColors title="Active vs closed" caption="Open work compared with finished applications" slices={[{key:'active',name:'Active',value:active.length},{key:'approved',name:'Approved',value:approved.length},{key:'declined',name:'Declined',value:cases.filter(c=>c.status==='declined').length},{key:'withdrawn',name:'Withdrawn',value:cases.filter(c=>c.status==='withdrawn').length}].filter(s=>s.value>0)} total={String(cases.length)} totalLabel="Total applications" onSelect={k=>onStage(k==='active'?'all':k)}/></div></>}
  {view==='risk'&&<><div className="chart-grid"><Donut title="Open exceptions by severity" caption="Evidence and policy referrals still open" slices={fold(severities.map(s=>({key:s,name:label(s),color:SEVERITY[s.toLowerCase()]||OTHER,value:exceptions.filter(e=>String(e.severity||'unspecified')===s).length})))} total={String(exceptions.length)} totalLabel="Total open" onSelect={()=>onExceptions()}/><Bars title="Promoter CIBIL score bands" caption={`Personal bureau score · ${scores.length} of ${cases.length} applications have a valid score`} rows={scoreBands.map(b=>({key:b.key,name:b.name,value:scores.filter(b.test).length})).concat([{key:'na',name:'Not available',value:cases.length-scores.length}])} format={n=>n+' cases'}/></div><div className="chart-grid"><Donut title="Document completeness" caption="Applications with every required document received" slices={[{key:'complete',name:'All documents received',value:docsComplete},{key:'missing',name:'Documents missing',value:cases.length-docsComplete}].filter(s=>s.value>0)} total={pct(docsComplete,cases.length)+'%'} totalLabel="Complete"/>{attention}</div></>}
  </div>
 </>
}
