'use client';
import InlineSelect from './inline-select';
import {useState} from 'react';
import {api,Data,money,label} from './api';
export default function ProductSettings({products,documents,admin,reload,report}:{products:Data[],documents:Data[],admin:boolean,reload:()=>Promise<void>,report:(s:string)=>void}){
 const [edit,setEdit]=useState<Data|null>(null),[result,setResult]=useState<Data|null>(null),[busy,setBusy]=useState(false);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!edit)return;const f=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await api('/products',{product:{...edit,...f,min_tenure:Number(f.min_tenure),max_tenure:Number(f.max_tenure)},expected_version:edit.revision||0,reason:f.reason});setEdit(null);await reload()}catch(e){report((e as Error).message)}finally{setBusy(false)}}
 return <><section className="panel"><div className="panel-heading"><div><h2>Loan products & interest settings</h2><p>Illustrative terms · Existing quotes retain their settings · Add credit-policy rules for new products</p></div></div><div className="table-scroll"><table><thead><tr><th>Product</th><th>Borrower</th><th>Base + spread</th><th>Rate limits</th><th>Interest method</th><th>Tenure</th><th>Documents</th><th/></tr></thead><tbody>{products.map(p=><tr key={p.key}><td><strong>{p.name}</strong></td><td>{label(p.borrower_type)}</td><td>{p.base_rate}% + {p.spread}%</td><td>{p.floor_rate}–{p.cap_rate}%</td><td>{label(p.method)}</td><td>{p.min_tenure}–{p.max_tenure} months</td><td>{p.documents.length} required</td><td>{admin&&<button className="btn small-btn" onClick={()=>setEdit({...p})}>Configure</button>}</td></tr>)}</tbody></table></div></section>
 {edit&&<section className="panel" style={{padding:24,marginTop:20}}><h2>{edit.name||'New loan product'}</h2><form onSubmit={save} key={edit.key}><div className="form-grid"><label>Product key<input name="key" required pattern="[a-z][a-z0-9_]{1,59}" defaultValue={edit.key} readOnly={!!products.find(p=>p.key===edit.key)}/></label><label>Product name<input name="name" required defaultValue={edit.name}/></label><label>Borrower type<InlineSelect name="borrower_type" defaultValue={edit.borrower_type}>{['business'].map(v=><option key={v}>{v}</option>)}</InlineSelect></label><label>Interest calculation<InlineSelect name="method" defaultValue={edit.method}><option value="reducing">Monthly reducing balance</option><option value="flat">Flat interest on original principal</option></InlineSelect></label>{[['base_rate','Base annual rate (%)'],['spread','Spread (percentage points)'],['floor_rate','Minimum annual rate (%)'],['cap_rate','Maximum annual rate (%)'],['min_tenure','Minimum tenure (months)'],['max_tenure','Maximum tenure (months)']].map(([k,n])=><label key={k}>{n}<input name={k} type="number" step={k.includes('tenure')?'1':'0.01'} required defaultValue={edit[k]}/></label>)}<fieldset className="span-two"><legend>Required evidence</legend><div className="form-grid">{documents.map(d=><label key={d.key} style={{display:'flex',flexDirection:'row',alignItems:'center'}}><input type="checkbox" style={{width:18}} checked={edit.documents.includes(d.key)} onChange={e=>setEdit({...edit,documents:e.target.checked?[...edit.documents,d.key]:edit.documents.filter((k:string)=>k!==d.key)})}/>{d.label}</label>)}</div></fieldset><label className="span-two">Reason for changing terms<textarea name="reason" required minLength={10}/></label></div><div className="modal-footer"><button type="button" className="btn" onClick={()=>setEdit(null)}>Cancel</button><button className="btn primary" disabled={busy}>Save product settings</button></div></form></section>}
 <section className="panel" style={{padding:24,marginTop:20}}><h2>Repayment calculator</h2><p>Annual rate = base + spread, bounded by the configured floor and cap.</p><form onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{setResult(await api('/products/quote',{...f,tenure:Number(f.tenure)}))}catch(e){report((e as Error).message)}}}><div className="form-grid"><label>Loan product<InlineSelect name="product">{products.map(p=><option value={p.key} key={p.key}>{p.name}</option>)}</InlineSelect></label><label>Principal (INR)<input name="amount" type="number" min="1" defaultValue="500000" required/></label><label>Tenure (months)<input name="tenure" type="number" min="1" max="600" defaultValue="36" required/></label><button className="btn primary" style={{alignSelf:'end'}}>Calculate repayment</button></div></form>{result&&<div className="note" role="status"><div><strong>{result.rate}% p.a. · {label(result.method)} · Monthly instalment {money(result.monthly_payment)}</strong><p>Total interest {money(result.total_interest)} · Total repayment {money(result.total_repayment)}</p><small>{result.notice}</small></div></div>}</section></>
}
