'use client';
import {Data,label,day} from './api';
import {fieldLabel,humanReason} from './financial-expression';
import {AlertTriangle,CheckCircle2,MinusCircle,Upload} from 'lucide-react';
function requirement(c:Data):string{if(!c)return 'See published policy';if(c.all||c.any)return (c.all||c.any).map(requirement).join(c.all?' and ':' or ');const op:Data={gte:'at least',lte:'at most',gt:'greater than',lt:'less than',eq:'equal to',ne:'different from',between:'between',present:'must be available',age_lte:'report age at most'};return `${fieldLabel(c.field||'Value')} ${op[c.op]||c.op} ${Array.isArray(c.value)?c.value.join(' and '):c.value??''}${c.op==='age_lte'?' days':''}`}
export default function StructuredAppraisal({assessment,detail,upload,explain,source}:{assessment:Data,detail:Data,upload:(key:string)=>void,explain:(key:string)=>void,source:(id:string)=>void}){
 const output=assessment.structured_output||{};
 const snap=assessment.snapshot||{};
 function checks(items:Data[],kind:string){return items.map((r:Data)=><article className={'assessment-item '+kind} key={r.id}><div className="assessment-item-title">{kind==='passed'?<CheckCircle2 size={18}/>:kind==='excluded'?<MinusCircle size={18}/>:<AlertTriangle size={18}/>}<strong>{r.name}</strong>{kind==='failed'&&<span className={'badge '+(r.severity==='blocking'?'fail':'warning')}>{r.severity==='blocking'?'Approval block':'Policy warning'}</span>}</div>{kind==='excluded'?<p>{r.reason||'This check does not apply to the selected facility.'}</p>:<><p><b>Policy requirement:</b> {requirement(r.condition)}</p><p><b>Recorded value:</b> {r.observed==null?'Unavailable':String(r.observed)}{r.reason&&<> · {humanReason(r.reason)}</>}</p>{(()=>{const fields=(c:Data):string[]=>c?.field?[c.field]:(c?.all||c?.any||[]).flatMap(fields);return fields(r.condition).map(key=>{const id=snap.source_ids?.[key];const fact=detail.fact?.find((f:Data)=>f.id===id);return fact?<p key={key} className="muted">{fieldLabel(key)} · {fact.source_text||'Recorded evidence'}{fact.document_id&&<button className="text-link" onClick={()=>source(fact.document_id)}>View source</button>}</p>:id?<p key={key} className="muted">{fieldLabel(key)} · Recorded in assessment input snapshot</p>:null})})()}</>}</article>)}
 const groups=[['Policy failures',output.policy_failures||[],'failed'],['Unable to assess',output.unable_to_assess||[],'unknown'],['Checks passed',output.passed_checks||[],'passed'],['Not applicable',output.not_applicable||[],'excluded']] as const;
 return <div className="structured-appraisal"><section className="assessment-next"><h3>Recommended next steps</h3><ul>{(output.next_steps||[]).map((s:string)=><li key={s}>{s}</li>)}</ul><small>Advisory assessment. The officer records the final decision.</small></section>
 {!!output.approval_holds?.length&&<section><h3>Approval holds</h3><ul>{output.approval_holds.map((gate:string)=><li key={gate}>{humanReason(gate)}</li>)}</ul></section>}
 {groups.slice(0,2).map(([name,items,kind])=><section key={name}><h3>{name} <span className="count">{items.length}</span></h3>{items.length?checks(items,kind):<p className="muted">None recorded in this assessment.</p>}</section>)}
 <section><h3>Missing documents <span className="count">{(output.missing_documents||[]).length}</span></h3>{!(output.missing_documents||[]).length&&<p className="muted">No missing required documents in this assessment.</p>}{(output.missing_documents||[]).map((name:string)=>{const doc=detail.document_checklist?.find((d:Data)=>d.label===name);const explanation=detail.evidence_explanation?.find((e:Data)=>e.document_type===doc?.key);return <article className="assessment-item unknown" key={name}><div className="assessment-item-title"><AlertTriangle size={18}/><strong>{name}</strong></div>{doc?.received?<p>Uploaded since this assessment. Await the updated assessment.</p>:<div className="assessment-actions">{doc&&<><button className="btn small-btn" onClick={()=>upload(doc.key)}><Upload size={15}/>Upload document</button><button className="text-link" onClick={()=>explain(doc.key)}>Record availability / explanation</button></>}</div>}{explanation&&<p><b>{label(explanation.availability)} — pending review:</b> {explanation.reason}<br/><small>{explanation.recorded_by} · {day(explanation.created_at)}</small></p>}</article>})}</section>
 {!!output.unverified_fields?.length&&<section><h3>Evidence awaiting verification</h3><p>{output.unverified_fields.map(fieldLabel).join(', ')}</p></section>}
 {!!(output.missing_documents?.length||output.unable_to_assess?.length)&&<section className="assessment-startup"><h3>New business / startup considerations</h3><p>If this is a new business, confirm whether GST history, existing loan records and a business credit report are available. Record a reason for anything not yet available or believed not applicable.</p><p>A missing rank is not a failed score. “No existing loans” needs a recorded declaration or supporting evidence. An availability explanation does not waive a policy requirement.</p></section>}
 {groups.slice(2).map(([name,items,kind])=><section key={name}><h3>{name} <span className="count">{items.length}</span></h3>{items.length?checks(items,kind):<p className="muted">None recorded in this assessment.</p>}</section>)}
 <section><h3>Additional notes</h3>{output.additional_notes?.length?<><p className="muted">Original model commentary / service notes. Policy results and evidence above remain authoritative.</p>{output.additional_notes.map((note:string,i:number)=><p key={i}>{note}</p>)}</>:<p className="muted">No additional notes.</p>}{(assessment.decision?.findings||[]).filter((f:Data)=>!(output.not_applicable||[]).some((r:Data)=>r.id===f.field||r.condition?.field===f.field)).map((f:Data,i:number)=><p key={'finding'+i}><b>{fieldLabel(f.field)}:</b> {f.observation}</p>)}</section>
 </div>
}
